modVersion=4.4.5-CFC
modGroup=hardcorequesting
modArchivesBaseName=HQM-The-Journey
modId=HardcoreQuesting
modName=Hardcore Questing Mode
modDescription=This mod will add Hardcore mode with extra lives. If you use up your lives, your world will be deleted or you will be banned.
modUrl=https://github.com/Xiaomo305Mua/HQMCFC
authorList=Vswe, Lorddusk, Newcastlegeek, Xiaomo305Mua
credits=
logoFile=assets/hqm/hqmlogo.png